# Generated by Django 3.1.7 on 2021-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_model', models.CharField(max_length=30)),
                ('product_size', models.IntegerField()),
                ('product_description', models.TextField(max_length=300, null=True)),
                ('product_stock', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('warranty', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=50)),
                ('image', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userTypeIndicator', models.IntegerField(auto_created=True, default=0)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=200, null=True)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]

    options = {
                  'managed': True,
              }