# Generated by Django 3.1.7 on 2021-04-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_genre', models.CharField(max_length=30)),
                ('product_number', models.IntegerField()),
                ('product_description', models.TextField(max_length=300, null=True)),
                ('product_stock', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('warranty', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('page_number', models.IntegerField()),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('year', models.IntegerField()),
                ('translator', models.CharField(max_length=50, null=True)),
                ('editor', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
